title: Nolan Can Read
description: Some books I have been reading (or listening to? Kind of counts?)

url: https://readings.of.nhawk.in/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10
mapping:
  provider: openstreetmap
  dimensions:
    width: 600
    height: 400

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Authors
    url: /authors
  - title: Map
    url: /map
